In [ ]:
#TASK01
class Student:
  ID = 0
  def __init__(self,name,dept,age,cgpa):
    self.name = name
    self.dept = dept
    self.age = age
    self.cgpa = cgpa
    Student.ID+=1
    self.Id = Student.ID
  def showDetails(self):
    print(f"ID: {self.Id}\nName: {self.name}\nDepartment: {self.dept}\nAge: {self.age}\nCGPA: {self.cgpa}")

  @classmethod
  def from_String(cls,info):
    info_list = info.split("-")
    return Student(info_list[0],info_list[1],info_list[2],info_list[3])

s1 = Student("Samin", "CSE", 21, 3.91)
s1.showDetails()
print("-----------------------")
s2 = Student("Fahim", "ECE", 21, 3.85)
s2.showDetails()
print("-----------------------")
s3 = Student("Tahura", "EEE", 22, 3.01)
s3.showDetails()
print("-----------------------")
s4 = Student.from_String("Sumaiya-BBA-23-3.96")
s4.showDetails()


print("============================================")
print("SUBTASK - 6")
print("Class variable is the variable of the whole class, Instance variable is the variable of a specific object")
print("============================================")
print("SUBTASK - 7")
print("Instace method is accessible by only specific object but class method is accessible by all the method")

ID: 1
Name: Samin
Department: CSE
Age: 21
CGPA: 3.91
-----------------------
ID: 2
Name: Fahim
Department: ECE
Age: 21
CGPA: 3.85
-----------------------
ID: 3
Name: Tahura
Department: EEE
Age: 22
CGPA: 3.01
-----------------------
ID: 4
Name: Sumaiya
Department: BBA
Age: 23
CGPA: 3.96

In [ ]:
#TASK02
class Assassin:
  num = 0
  def __init__(self,name,rate):
    self.name = name
    self.rate = rate
    Assassin.num += 1
    self.num = Assassin.num
  def printDetails(self):
    print(f"Name: {self.name}\nSuccess Rate: {self.rate}%\nTotal Numbers of Assassin: {self.num}")
  @classmethod
  def failureRate(cls,name,frate):
    return Assassin(name,100-frate)
  @classmethod
  def failurePercentage(cls,name,percantage):
    percantage = int(percantage.replace("%",""))
    return Assassin(name,100-percantage)

john_wick = Assassin('John Wick', 100)
john_wick.printDetails()
print('================================')
nagisa = Assassin.failureRate("Nagisa", 20)
nagisa.printDetails()
print('================================')
akabane = Assassin.failurePercentage("Akabane", "10%")
akabane.printDetails()

Name: John Wick
Success Rate: 100%
Total Numbers of Assassin: 1
================================
Name: Nagisa
Success Rate: 80%
Total Numbers of Assassin: 2
================================
Name: Akabane
Success Rate: 90%
Total Numbers of Assassin: 3

In [ ]:
#TASK03
class Passenger:
  count = 0
  def __init__(self,name):
    self.name = name
    self.fare = 0
    Passenger.count+=1
    self.count = Passenger.count
  def set_bag_weight(self, weight):
    self.weight = weight
    if 21<=self.weight<=50:
      self.fare = 50
    elif self.weight>50:
      self.fare = 100



  def printDetail(self):
    print(f"Name: {self.name}")
    print(f"Bus Fare: {450+self.fare}")

print("Total Passenger:", Passenger.count)
p1 = Passenger("Jack")
p1.set_bag_weight(90)
p2 = Passenger("Carol")
p2.set_bag_weight(10)
p3 = Passenger("Mike")
p3.set_bag_weight(25)
print("=========================")
p1.printDetail()
print("=========================")
p2.printDetail()
print("=========================")
p3.printDetail()
print("=========================")
print("Total Passenger:", Passenger.count)

Total Passenger: 0
=========================
Name: Jack
Bus Fare: 550
=========================
Name: Carol
Bus Fare: 450
=========================
Name: Mike
Bus Fare: 500
=========================
Total Passenger: 3

In [ ]:
#TASK04
class Travel:
  count = 0
  def __init__(self,start,end,time = 1):
    self.start = start
    self.end = end
    self.time = time
    Travel.count+=1
  def set_time(self,new):
    self.time = new
  def set_destination(self,new):
    self.end = new
  def set_source(self,new):
    self.start = new
  def display_travel_info(self):
    return (f"Source: {self.start}\nDestination: {self.end}\nFlight Time:{self.time}:00")



print("No. of Traveller =", Travel.count)
print("=======================")
t1 = Travel("Dhaka","India")
print(t1.display_travel_info())
print("=======================")
t2 = Travel("Kuala Lampur","Dhaka")
t2.set_time(23)
print(t2.display_travel_info())
print("=======================")
t3 = Travel("Dhaka","New_Zealand")
t3.set_time(15)
t3.set_destination("Germany")
print(t3.display_travel_info())
print("=======================")
t4 = Travel("Dhaka","India")
t4.set_time(9)
t4.set_source("Malaysia")
t4.set_destination("Canada")
print(t4.display_travel_info())
print("=======================")
print("No. of Traveller =", Travel.count)

No. of Traveller = 0
=======================
Source: Dhaka
Destination: India
Flight Time:1:00
=======================
Source: Kuala Lampur
Destination: Dhaka
Flight Time:23:00
=======================
Source: Dhaka
Destination: Germany
Flight Time:15:00
=======================
Source: Malaysia
Destination: Canada
Flight Time:9:00
=======================
No. of Traveller = 4

In [ ]:
#TASK05
class Employee:
  def __init__(self,name,year):
    self.name = name
    self.workingPeriod = year
  @classmethod
  def employeeByJoiningYear(cls,name,year):
    return Employee(name,2023-year)
  @staticmethod
  def experienceCheck(year,gender):
    if year<3:
      if gender == "male":
        return "He is not experienced"
      else:
        return "She is not experienced"
    else:
      if gender == "male":
       return "He is experienced"
      else:
       return "She is experienced"


employee1 = Employee('Dororo', 3)
employee2 = Employee.employeeByJoiningYear('Harry', 2016)
print(employee1.workingPeriod)
print(employee2.workingPeriod)
print(employee1.name)
print(employee2.name)
print(Employee.experienceCheck(2, "male"))
print(Employee.experienceCheck(3, "female"))

3
7
Dororo
Harry
He is not experienced
She is experienced

In [ ]:
#TASK06
class Laptop:
  laptopCount = 0
  def __init__(self,name,count):
    self.name = name
    self.count = count
    Laptop.laptopCount += count
  def advantage():
    print("Laptops are portable")
  @classmethod
  def resetCount(cls):
    cls.laptopCount = 0

lenovo = Laptop("Lenovo", 5)
dell = Laptop("Dell", 7)
print(lenovo.name, lenovo.count)
print(dell.name, dell.count)
print("Total number of Laptops", Laptop.laptopCount)
Laptop.advantage()
Laptop.resetCount()
print("Total number of Laptops", Laptop.laptopCount)

Lenovo 5
Dell 7
Total number of Laptops 12
Laptops are portable
Total number of Laptops 0

In [ ]:
#TASK07
class Cat:
  Number_of_cats = 0
  def __init__(self,color,work):
    self.color = color
    self.work = work
    Cat.Number_of_cats += 1
  @classmethod
  def no_parameter(cls):
    return Cat("White","sitting")
  @classmethod
  def first_parameter(cls,color):
    return Cat(color,"sitting")
  @classmethod
  def second_parameter(cls,work):
    return Cat("Grey",work)
  def changeColor(self,new):
    self.color = new
  def printCat(self):
    print(f"{self.color} is {self.work}")


print("Total number of cats:", Cat.Number_of_cats)
c1 = Cat.no_parameter()
c2 = Cat.first_parameter("Black")
c3 = Cat("Brown", "jumping")
c4 = Cat("Red", "purring")
c5 = Cat.second_parameter("playing")
print("=======================")
c1.printCat()
c2.printCat()
c3.printCat()
c4.printCat()
c5.printCat()
c1.changeColor("Blue")
c3.changeColor("Purple")
c1.printCat()
c3.printCat()
print("=======================")
print("Total number of cats:", Cat.Number_of_cats)

Total number of cats: 0
=======================
White is sitting
Black is sitting
Brown is jumping
Red is purring
Grey is playing
Blue is sitting
Purple is jumping
=======================
Total number of cats: 5

In [ ]:
#TASK08
import math
class Cylinder:
  radius = 5
  height = 18
  def __init__(self,radius,height):
    print(f"Default radius= {Cylinder.radius} and height = {Cylinder.height}.")
    Cylinder.radius = radius
    Cylinder.height = height
    self.radius = radius
    self.height = height
    print(f"Updated radius= {Cylinder.radius} and height= {Cylinder.height}.")

  @staticmethod
  def area(radius,height):
    print(f"Area : {float((2*math.pi*radius**2) + (2*math.pi*radius*height))}")

  @staticmethod
  def volume(radius,height):
    print(f"Volume : {float(math.pi*radius**2*height)}")

  @classmethod
  def swap(cls,height,radius):
    return Cylinder(radius,height)
  @classmethod
  def changeFormat(cls,string):
    data_list = string.split("-")
    return Cylinder(float(data_list[0]),float(data_list[1]))








c1 = Cylinder(0,0)
Cylinder.area(c1.radius,c1.height)
Cylinder.volume(c1.radius,c1.height)
print("===============================")
c2 = Cylinder.swap(8,3)
c2.area(c2.radius,c2.height)
c2.volume(c2.radius,c2.height)
print("===============================")
c3 = Cylinder.changeFormat("7-13")
c3.area(c3.radius,c3.height)
c3.volume(c3.radius,c3.height)
print("===============================")
Cylinder(0.3,5.56).area(Cylinder.radius,Cylinder.height)
print("===============================")
Cylinder(3,5).volume(Cylinder.radius,Cylinder.height)

Default radius= 5 and height = 18.
Updated radius= 0 and height= 0.
Area : 0.0
Volume : 0.0
===============================
Default radius= 0 and height = 0.
Updated radius= 3 and height= 8.
Area : 207.34511513692635
Volume : 226.1946710584651
===============================
Default radius= 3 and height = 8.
Updated radius= 7.0 and height= 13.0.
Area : 879.645943005142
Volume : 2001.1945203366981
===============================
Default radius= 7.0 and height = 13.0.
Updated radius= 0.3 and height= 5.56.
Area : 11.045839770021713
===============================
Default radius= 0.3 and height = 5.56.
Updated radius= 3 and height= 5.
Volume : 141.3716694115407

In [ ]:
#TASK09
class Student:
  Total = 0
  Brac = 0
  Other = 0
  def __init__(self,name, department, Uni = "BRAC University"):
    self.name = name
    self.department = department
    self.Uni = Uni
    if Uni == "BRAC University":
      Student.Brac += 1
    else:
      Student.Other +=1
    Student.Total +=1

  def individualDetail(self):
    print(f"Name: {self.name}\nDepartment: {self.department}\nInstitution: {self.Uni}")

  @classmethod
  def createStudent(cls,name, department, Uni = "BRAC University"):
    return Student(name, department, Uni)
  @classmethod
  def printDetails(cls):
    print(f"Total Student(s): {cls.Total}\nBRAC University Student(s): {cls.Brac}  \nOther Institution Student(s): {cls.Other} ")

Student.printDetails()
print('#########################')

mikasa = Student('Mikasa Ackerman', "CSE")
mikasa.individualDetail()
print('------------------------------------------')
Student.printDetails()

print('========================')

harry = Student.createStudent('Harry Potter', "Defence Against Dark Arts", "Hogwarts School")
harry.individualDetail()
print('-------------------------------------------')
Student.printDetails()

print('=========================')

levi = Student.createStudent("Levi Ackerman", "CSE")
levi.individualDetail()
print('--------------------------------------------')
Student.printDetails()

Total Student(s): 0
BRAC University Student(s): 0
Other Institution Student(s): 0
#########################
Name: Mikasa Ackerman
Department: CSE
Institution: BRAC University
------------------------------------------
Total Student(s): 1
BRAC University Student(s): 1
Other Institution Student(s): 0
========================
Name: Harry Potter
Department: Defence Against Dark Arts
Institution: Hogwarts School
-------------------------------------------
Total Student(s): 2
BRAC University Student(s): 1
Other Institution Student(s): 1
=========================
Name: Levi Ackerman
Department: CSE
Institution: BRAC University
--------------------------------------------
Total Student(s): 3
BRAC University Student(s): 2
Other Institution Student(s): 1

In [ ]:
#TASK10
class SultansDine:
  Total_branch = 0
  Total_sell = 0
  branch_list = []
  def __init__(self,branch):
    self.branch = branch
    self.sell = 0
    self.branch_dic = {}
    SultansDine.Total_branch += 1
  def sellQuantity(self,sell):
    if sell<10:
      self.sell = sell*300
    elif sell<20:
      self.sell = sell*350
    else:
      self.sell = sell*400
    SultansDine.Total_sell += self.sell
    self.branch_dic[self.branch] = self.sell
    SultansDine.branch_list.append(self.branch_dic)

  def branchInformation(self):
    print(f"Branch Name: {self.branch}\nBranch Sell: {self.sell}")

  @classmethod
  def details(cls):
    print(f"Total Number of branch(s): {cls.Total_branch}")
    print(f"Total Sell: {cls.Total_sell} Taka")
    for i in cls.branch_list:
      for j in i:
        print(f"Branch Name: {j}, Branch Sell: {i[j]} Taka\nBranch consists of total sell's: {round((i[j]/cls.Total_sell)*100,2)}%")



SultansDine.details()
print('########################')
dhanmondi = SultansDine('Dhanmondi')
dhanmondi.sellQuantity(25)
dhanmondi.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()

Total Number of branch(s): 0
Total Sell: 0 Taka
########################
Branch Name: Dhanmondi
Branch Sell: 10000
-----------------------------------------
Total Number of branch(s): 1
Total Sell: 10000 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 100.0%
========================
Branch Name: Baily Road
Branch Sell: 5250
-----------------------------------------
Total Number of branch(s): 2
Total Sell: 15250 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 65.57%
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch consists of total sell's: 34.43%
========================
Branch Name: Gulshan
Branch Sell: 2700
-----------------------------------------
Total Number of branch(s): 3
Total Sell: 17950 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 55.71%
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch consists of total sell's: 29.25%
Branch Name: Gulshan, Branch Sell: 2700 Taka
Branch consists of total sell's: 15.04%